### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [5]:
import pandas as pd
import numpy as np

In [6]:
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])

df = pd.read_csv('cars.csv',delimiter=';')
display(df)

Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70      US  
1    3693.0          11.5     70      US  
2    3436.0          11.0     70      US  
3    3433.0          12.0     70      US  
4    3449.0          10.5     70      US  
..      ...           ...    ...     ...  
401  2790.0          15.6     82      US  
402  2130.0          24.6     82  Europe  
403  2295.0          11.6     82      US  
404  2625.0          18.6     82      US  
405  2720.0          19.4     82      US  

[406 rows x 9 columns]

1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [ ]:
1.To make a numpy array, you can just use the np.array() function and pass a list to it.
you can also specify a datatype of data. 

In [72]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [22]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [83]:
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [4]:
import numpy as np
arr = np.array(['Car', 'mpg', 'horsepower', 'origin'])
print(arr.dtype)

<U10


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
# NumPy is a library for the Python programming language and it supports for a large arrays called numarrays.
# NumPy is an N-dimensional array type called ndarray. ... so for large no of array we generally it writtens as 
import numpy as np.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [2]:

import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [79]:
car.ndim

1

In [80]:
mpg.ndim

1

In [3]:
cylinders.ndim

1

5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [27]:

import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)


                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [28]:
mpg * 12

array([216. , 180. , 216. , 192. , 204. , 180. , 168. , 168. , 168. ,
       180. ,   0. ,   0. ,   0. ,   0. ,   0. , 180. , 168. ,   0. ,
       180. , 168. , 288. , 264. , 216. , 252. , 324. , 312. , 300. ,
       288. , 300. , 312. , 252. , 120. , 120. , 132. , 108. , 324. ,
       336. , 300. , 300. ,   0. , 228. , 192. , 204. , 228. , 216. ,
       168. , 168. , 168. , 168. , 144. , 156. , 156. , 216. , 264. ,
       228. , 216. , 276. , 336. , 360. , 360. , 372. , 420. , 324. ,
       312. , 288. , 300. , 276. , 240. , 252. , 156. , 168. , 180. ,
       168. , 204. , 132. , 156. , 144. , 156. , 228. , 180. , 156. ,
       156. , 168. , 216. , 264. , 252. , 312. , 264. , 336. , 276. ,
       336. , 324. , 156. , 168. , 156. , 168. , 180. , 144. , 156. ,
       156. , 168. , 156. , 144. , 156. , 216. , 192. , 216. , 216. ,
       276. , 312. , 132. , 144. , 156. , 144. , 216. , 240. , 252. ,
       264. , 216. , 228. , 252. , 312. , 180. , 192. , 348. , 288. ,
       240. , 228. ,

In [29]:
mpg / 3

array([ 6.        ,  5.        ,  6.        ,  5.33333333,  5.66666667,
        5.        ,  4.66666667,  4.66666667,  4.66666667,  5.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        5.        ,  4.66666667,  0.        ,  5.        ,  4.66666667,
        8.        ,  7.33333333,  6.        ,  7.        ,  9.        ,
        8.66666667,  8.33333333,  8.        ,  8.33333333,  8.66666667,
        7.        ,  3.33333333,  3.33333333,  3.66666667,  3.        ,
        9.        ,  9.33333333,  8.33333333,  8.33333333,  0.        ,
        6.33333333,  5.33333333,  5.66666667,  6.33333333,  6.        ,
        4.66666667,  4.66666667,  4.66666667,  4.66666667,  4.        ,
        4.33333333,  4.33333333,  6.        ,  7.33333333,  6.33333333,
        6.        ,  7.66666667,  9.33333333, 10.        , 10.        ,
       10.33333333, 11.66666667,  9.        ,  8.66666667,  8.        ,
        8.33333333,  7.66666667,  6.66666667,  7.        ,  4.33

In [32]:
x = np.sqrt(mpg)
x

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

In [33]:
mpg **4

array([ 104976.    ,   50625.    ,  104976.    ,   65536.    ,
         83521.    ,   50625.    ,   38416.    ,   38416.    ,
         38416.    ,   50625.    ,       0.    ,       0.    ,
             0.    ,       0.    ,       0.    ,   50625.    ,
         38416.    ,       0.    ,   50625.    ,   38416.    ,
        331776.    ,  234256.    ,  104976.    ,  194481.    ,
        531441.    ,  456976.    ,  390625.    ,  331776.    ,
        390625.    ,  456976.    ,  194481.    ,   10000.    ,
         10000.    ,   14641.    ,    6561.    ,  531441.    ,
        614656.    ,  390625.    ,  390625.    ,       0.    ,
        130321.    ,   65536.    ,   83521.    ,  130321.    ,
        104976.    ,   38416.    ,   38416.    ,   38416.    ,
         38416.    ,   20736.    ,   28561.    ,   28561.    ,
        104976.    ,  234256.    ,  130321.    ,  104976.    ,
        279841.    ,  614656.    ,  810000.    ,  810000.    ,
        923521.    , 1500625.    ,  531441.    ,  45697

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [34]:

import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)


                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [35]:
#sum of horsepower
sum(horsepower)

42033.0

In [36]:
min(horsepower)

0.0

In [37]:
max(horsepower)

230.0

In [40]:
#median
a = np.median(horsepower)
a

93.5

In [43]:
#mode
import numpy as np
from scipy import stats
m = stats.mode(horsepower)
print(m)

ModeResult(mode=array([150.]), count=array([22]))


7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [4]:

import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [6]:
#select only the first five elements
import numpy as np
print (acceleration[0:5])

[12.  11.5 11.  12.  10.5]


In [7]:
#Select every other element (new selection)
print(acceleration[::2])

[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 14.7 14.5 16.9
 15.7 16.4 1

8. Show how to select the number `99` in the array below. 

In [ ]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [6]:
import numpy as np
select_99 = np.array([[1,2,3],
                      [4,5,99]])


In [7]:
select_99

array([[ 1,  2,  3],
       [ 4,  5, 99]])

In [13]:
select_99[1][2]

99

9. Select the last element in each subarray (do this with one operation.)

In [18]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [27]:
import numpy as np

select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(select_more[0:3, 2])


[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [ ]:
import numpy as np
x = np.lookfor('log')
print(x)

In [10]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [13]:
np.log2(mpg)

array([4.169925  , 3.9068906 , 4.169925  , 4.        , 4.08746284,
       3.9068906 , 3.80735492, 3.80735492, 3.80735492, 3.9068906 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       3.9068906 , 3.80735492,       -inf, 3.9068906 , 3.80735492,
       4.5849625 , 4.45943162, 4.169925  , 4.39231742, 4.7548875 ,
       4.70043972, 4.64385619, 4.5849625 , 4.64385619, 4.70043972,
       4.39231742, 3.32192809, 3.32192809, 3.45943162, 3.169925  ,
       4.7548875 , 4.80735492, 4.64385619, 4.64385619,       -inf,
       4.24792751, 4.        , 4.08746284, 4.24792751, 4.169925  ,
       3.80735492, 3.80735492, 3.80735492, 3.80735492, 3.5849625 ,
       3.70043972, 3.70043972, 4.169925  , 4.45943162, 4.24792751,
       4.169925  , 4.52356196, 4.80735492, 4.9068906 , 4.9068906 ,
       4.95419631, 5.12928302, 4.7548875 , 4.70043972, 4.5849625 ,
       4.64385619, 4.52356196, 4.32192809, 4.39231742, 3.70043972,
       3.80735492, 3.9068906 , 3.80735492, 4.08746284, 3.45943

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [ ]:
The unique() function is used to find the unique elements of an array.

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [49]:
# createing a 2D array
import numpy as np
a = np.array(([2,3,4,5],[6,7,8,9]))

In [65]:
a
print("shape:", a.shape)
print("Dimension:", a.ndim)

shape: (2, 4)
Dimension: 2


In [75]:
# create 3D array
import numpy as np
b = np.array([[[1,2,3,4],[5,6,7,8],
               [1,1,5,7],[1,3,9,7]]])
print("shape:", b.shape)
print("Diamension:", b.ndim)

shape: (1, 4, 4)
Diamension: 3


In [76]:
b

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 1, 5, 7],
        [1, 3, 9, 7]]])

In [77]:
# create 4D array
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
a = np.expand_dims(a, axis=0)
a = np.repeat(a, 4, axis=0)

In [78]:
a

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]]])

In [80]:
print("shape:",a.shape)
print("Dimension:",a.ndim)

shape: (4, 3, 2, 3)
Dimension: 4


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [57]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [62]:
origin == "US"

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [48]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [18]:
car[origin == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

In [17]:
origin == "US"
    

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [ ]:
An identity matrix is a square matrix having 1s on the main diagonal, and zeros everwhere else.

In [2]:
import numpy as np


In [6]:
 I = np.identity(5)


In [7]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [8]:
import numpy as np

In [11]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

transpose_me.transpose((1, 0))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [17]:
import numpy as np


In [18]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])


In [19]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
res = np.dot(arr1, arr2) 
 
print(res) 

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [1]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [5]:
horsepower_average = horsepower [origin == 'Europe']
hpavg = np.mean(horsepower_average)
print(hpavg)

78.78082191780823


In [16]:
x = origin == 'US'
print(x)
arr = car[x]
print(arr)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

5. On average are Japanse cars more fuel efficient than US cars? 

In [8]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [13]:
japanse_avg = mpg [origin == 'japanse']
jap_avg = np.mean(japanse_avg)
print(jap_avg)


nan


6. What is the correlation coefficient of `mpg` and `weight`?

In [25]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('Documents/Data-Science-Assignments/course_material/week_03/cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(df)

                           Car   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0          8         307.0       130.0   
1            Buick Skylark 320  15.0          8         350.0       165.0   
2           Plymouth Satellite  18.0          8         318.0       150.0   
3                AMC Rebel SST  16.0          8         304.0       150.0   
4                  Ford Torino  17.0          8         302.0       140.0   
..                         ...   ...        ...           ...         ...   
401            Ford Mustang GL  27.0          4         140.0        86.0   
402          Volkswagen Pickup  44.0          4          97.0        52.0   
403              Dodge Rampage  32.0          4         135.0        84.0   
404                Ford Ranger  28.0          4         120.0        79.0   
405                 Chevy S-10  31.0          4         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0     70

In [33]:
#scipy import stats
x = np.corrcoef(mpg,weight)
print(x)

[[ 1.         -0.78750994]
 [-0.78750994  1.        ]]


7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
# Numpy arrays consumes less memory.
Numpy arrays are fast comparitively python list and it is more conveniant to use when we want to do mathematical operations.
# python list preferred 
python list having different datatypes. we can store different datatypes in list like int, float, string in a list.
in Numpy array we can store a same datatype.u cant have different datatypes in a singal array.